# Generated by Django 5.0.2 on 2024-02-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
    ]
