# Generated by Django 4.2.11 on 2024-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0003_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_comment', models.CharField(max_length=1000)),
                ('report_location', models.CharField(max_length=200)),
                ('report_file', models.FileField(upload_to='')),
            ],
        ),
    ]
