# Generated by Django 5.0.2 on 2024-03-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='b26.userprofile'),
        ),
    ]
