# Generated by Django 5.0.2 on 2024-03-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0005_report_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='b26.report'),
        ),
    ]
