# Generated by Django 5.0.2 on 2024-03-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0006_remove_report_report_file_fileupload_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name_plural': 'File Uploads'},
        ),
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='New', max_length=20),
        ),
    ]
