# Generated by Django 5.0.2 on 2024-03-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0007_alter_fileupload_options_report_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
