# Generated by Django 5.0.2 on 2024-04-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0008_report_report_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Noise', 'Noise'), ('Maintenance', 'Maintenance'), ('Sanitation', 'Sanitation'), ('Safety', 'Safety'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
