# Generated by Django 4.2.11 on 2024-04-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0009_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_location',
            field=models.CharField(choices=[('Balz-Dobie', 'Balz-Dobie'), ('Cauthen', 'Cauthen'), ('Gibbons', 'Gibbons'), ('Kellogg', 'Kellogg'), ('Lile-Maupin', 'Lile-Maupin'), ('Shannon', 'Shannon'), ('Tuttle-Dunnington', 'Tuttle-Dunnington'), ('Watson-Webb', 'Watson-Webb'), ('Woody', 'Woody'), ('Courtenay', 'Courtenay'), ('Dunglison', 'Dunglison'), ('Fitzhugh', 'Fitzhugh'), ('Brown College', 'Brown College'), ('Gooch', 'Gooch'), ('Dillard', 'Dillard'), ('Hereford College', 'Hereford College'), ('International Residential College', 'International Residential College'), ('Bonnycastle', 'Bonnycastle'), ('Dabney', 'Dabney'), ('Echols', 'Echols'), ('Emmet', 'Emmet'), ('Hancock', 'Hancock'), ('Humphreys', 'Humphreys'), ('Kent', 'Kent'), ('Lefevre', 'Lefevre'), ('Metcalf', 'Metcalf'), ('Page', 'Page'), ('Bice', 'Bice'), ('Bond', 'Bond'), ('Copeley', 'Copeley'), ('Faulkner', 'Faulkner'), ('Lambeth', 'Lambeth'), (' French House', 'French House'), ('Spanish House', 'Spanish House'), ('Shea House', 'Shea House')], default='Balz-Dobie', max_length=250),
        ),
    ]
