# Generated by Django 5.0.2 on 2024-04-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0009_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Make report public'),
        ),
        migrations.AddField(
            model_name='report',
            name='public_description',
            field=models.BooleanField(default=False, verbose_name='Public Description'),
        ),
        migrations.AddField(
            model_name='report',
            name='public_files',
            field=models.BooleanField(default=False, verbose_name='Public Files'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_location',
            field=models.CharField(choices=[('Balz-Dobie', 'Balz-Dobie'), ('Cauthen', 'Cauthen'), ('Gibbons', 'Gibbons'), ('Kellogg', 'Kellogg'), ('Lile-Maupin', 'Lile-Maupin'), ('Shannon', 'Shannon'), ('Tuttle-Dunnington', 'Tuttle-Dunnington'), ('Watson-Webb', 'Watson-Webb'), ('Woody', 'Woody'), ('Courtenay', 'Courtenay'), ('Dunglison', 'Dunglison'), ('Fitzhugh', 'Fitzhugh'), ('Brown College', 'Brown College'), ('Gooch', 'Gooch'), ('Dillard', 'Dillard'), ('Hereford College', 'Hereford College'), ('International Residential College', 'International Residential College'), ('Bonnycastle', 'Bonnycastle'), ('Dabney', 'Dabney'), ('Echols', 'Echols'), ('Emmet', 'Emmet'), ('Hancock', 'Hancock'), ('Humphreys', 'Humphreys'), ('Kent', 'Kent'), ('Lefevre', 'Lefevre'), ('Metcalf', 'Metcalf'), ('Page', 'Page'), ('Bice', 'Bice'), ('Bond', 'Bond'), ('Copeley', 'Copeley'), ('Faulkner', 'Faulkner'), ('Lambeth', 'Lambeth'), (' French House', 'French House'), ('Spanish House', 'Spanish House'), ('Shea House', 'Shea House')], default='Balz-Dobie', max_length=250),
        ),
    ]
