# Generated by Django 4.2.10 on 2024-04-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0009_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upvoted', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='b26.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b26.userprofile')),
            ],
            options={
                'unique_together': {('user', 'report')},
            },
        ),
    ]
