# Generated by Django 4.2.11 on 2024-04-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b26', '0010_report_is_public_report_public_description_and_more'),
        ('b26', '0010_report_report_title_alter_report_report_location'),
    ]

    operations = [
    ]
